---
title: "Development actions history"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r description, eval=FALSE}
# Describe your package
fusen::fill_description(
  pkg = here::here(),
  fields = list(
    Title = "Simulated Survey Of Megafauna At Offshore Windfarms",
    Description = "Ce package contient de nombreuses fonctions permettant de simuler des données de suivis aérien. Ce package permet de simuler différentes abondance de population, différents échnatillonnages ainsi que de simuler différents méthodes de survols aériens.",
    `Authors@R` = c(
      person("Maud", "Queroue", email = "maud.queroue@gmail.com", role = c("aut", "cre"))
    )
  ),
  overwrite = TRUE
)
# Define License with use_*_license()
usethis::use_mit_license("Maud Queroue")
```

# Start using git

```{r, eval=FALSE}
usethis::use_git()
```

# Set extra sources of documentation

```{r, eval=FALSE}
# README
usethis::use_readme_rmd()
# Code of Conduct
usethis::use_code_of_conduct("maud.queroue@gmail.com")
# NEWS
#usethis::use_news_md()
```


# Package development tools

```{r, eval=FALSE}
# Pipe
usethis::use_pipe()

# Data
usethis::use_data_raw()

# package-level documentation
#usethis::use_package_doc()

# Set CI
# _GitHub
# usethis::use_github_action_check_standard()
# usethis::use_github_action("pkgdown")
# usethis::use_github_action("test-coverage")


```

## Use everytime needed

```{r}
# Simulate package installation
pkgload::load_all()

# Generate documentation and deal with dependencies
attachment::att_amend_desc()

# Check the package
devtools::check()
```



# code coverage 
```{r}
covr::report()
```



# Share the package

```{r}
# set and try pkgdown documentation website
usethis::use_pkgdown()
pkgdown::build_site()

# build the tar.gz to share with others
devtools::build()
```

