---
title: "flat_sampling_design_emulator.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

# My function
# proposer segmentize, and crop considering the grid. 

```{r function-create_transects}

#' Create transect
#'
#' @param shape_obj sf object. The shape of the study site.
#' @param design character. Variable describing the type of design. Either "random", "systematic", "eszigzag" (equal-spaced zigzag), "eszigzagcom" (equal spaced zigzag with complementary lines) or "segmentedgrid". See dssd package for more information.
#' @param design.angle numeric. Value detailing the angle of the design. A value of -1 will cause a random design angle to be generated. See dssd package for more information. Bydefault = 0.
#' @param line.length numeric. The approximative total line length desired (in m).
#' @param segmentize boolean. TRUE = transects are segmentized and a seg_ID is given to each segment. FALSE = transects are not segmentized. By default = FALSE.
#' @param length_segs numeric. Length of the segments desired.
#' @param crs numeric. Projection system. By default = 2154.
#' @param ... All other arguments that could be used in the make.design function. See dssd package for more information.
#'
#' @importFrom dssd make.design generate.transects
#' @importFrom sf st_cast st_sf st_geometry st_multilinestring st_sfc st_coordinates st_set_geometry st_crs st_geometry_type st_segmentize st_length st_union st_intersection
#' @importFrom dplyr select mutate
#' @importFrom assertthat assert_that
#' @importFrom units set_units
#'
#' @return sf object. The created transects.
#' @export

create_transects <- function(shape_obj, design = "systematic", design.angle = 0, line.length, segmentize = FALSE, length_segs, crs = 2154, ...) {
  
  # Function checks
  assert_that(inherits(shape_obj, "sf"))
  assert_that(is.numeric(crs))
  assert_that(is.character(design))
  assert_that(is.numeric(line.length))
  assert_that(is.numeric(design.angle))

  # Function
  shape_obj <- shape_obj %>%
    st_transform(crs = crs) %>%
    st_union()
  
  
  region_obj <- make.region(region.name = "Study site",
                            shape = shape_obj,
                            units = "m")
  
  transect.design <- make.design(region = region_obj,
                                 design = design,
                                 design.angle = design.angle,
                                 line.length = line.length,
                                 ...)
  
  transect.survey <- generate.transects(transect.design)
  
  x <- transect.survey@samplers %>%
    as.data.frame() %>%
    select("transect","geometry") %>%
    st_sf(crs = crs) %>%
    st_cast("LINESTRING")
  
if(segmentize == TRUE){
  
  ### Segmentize
  #-----------------
  assert_that(is.numeric(length_segs))
  
  transect_obj <- st_segmentize(x, dfMaxLength = set_units(length_segs, "metres"))
  # geometry
  ggg <- st_geometry(transect_obj)
  
  # check
  if (isFALSE(st_geometry_type(ggg) %in% c("LINESTRING"))) {
    stop("Input should be LINESTRING")
  }
  
  # loop to segmentize
  for (k in 1:length(st_geometry(ggg))) {
    # segment in each transect as sf multilinestring
    sub <- ggg[k]
    geom <- lapply(1:(length(st_coordinates(sub)[, 1]) - 1),
      function(i)rbind(as.numeric(st_coordinates(sub)[i, 1:2]), as.numeric(st_coordinates(sub)[i + 1, 1:2]))) %>%
      st_multilinestring() %>%
      st_sfc()
    # create endgeom with the multilinestring for each transect
    if (k == 1) {endgeom <- geom}
    else {endgeom <- rbind(endgeom, geom)}
  }
  
  # sf object
  endgeom <- endgeom %>% 
    st_sfc(crs = crs) 

  # Multilinestring to linestring
  endgeom <- st_set_geometry(transect_obj, endgeom) %>% 
    st_cast("LINESTRING") 
  
  ### Add effort
  #----------------
  endgeom$effort <- st_length(endgeom)
  
  ### Name segment
  #-----------------
  endgeom$seg_ID <- NA
  # loop over the transect IDs
  for(this_transect in unique(endgeom$transect)){
    # how many segments in this transect?
    n_segs <- nrow(subset(endgeom, transect==this_transect))
    # generate the n_segs labels that we need
    endgeom$seg_ID[endgeom$transect==this_transect] <- paste(this_transect, 1:n_segs, sep="-")}
  
  x <- endgeom
  }
  
  if(segmentize == FALSE){
    x <- x %>% 
      mutate(seg_ID = transect)
  }
  
  return(x)
}

```

### Example

For this example, we used a `shape_obj` that is included in this package `shape_courseulles`. From this region object, we created : 
- (1) systematic parallel transects with a approximative length of 400000m
- (2) zigzag transects with a approximative length of 400000m that are segmentized with a length of 2000m per segment. 

```{r examples-create_transects}

library(ggplot2)
data("shape_courseulles")

# ------------------------------
# Example 1 : systematic parallel transects with a approximative total length of 400000m

transects <- create_transects(shape_obj = shape_courseulles,
                             design = "systematic",
                             line.length = 400000)
# Plot
ggplot() +
      geom_sf(data = shape_courseulles) +
      geom_sf(data = transects) 


# ------------------------------
# Example 2 : zigzag transects with a approximative total length of 400000m 
# that are segmentized with a length of 2000m per segment
transects <- create_transects(shape_obj = shape_courseulles,
                             design = "eszigzag",
                             line.length = 400000,
                             design.angle = 90,
                             segmentize = TRUE,
                             length_segs = 2000)

# Plot
pal <- rep(c("#98C1D9","#EE6C4D","#293241"),nrow(transects)) 
ggplot() +
      geom_sf(data = shape_courseulles) +
      geom_sf(data = transects, aes(colour = seg_ID))+
      scale_colour_manual(values=pal) +
      theme(legend.position = "none")



# ------------------------------
# Example 3 : systematic parallel transects with a approximative total length of 400000m
# that are segmentized with a length of 2000m per segment 
# and crop according to the map_obj grid containing densities

# Create map 
map <- create_density_map(shape_obj = shape_courseulles,
                              N = 200,
                              grid_size = 1000,
                              density_type = "gradient",
                              gradient_direction = "N",
                              wavelength = 20000,
                              amplitude = 500)

# Create transects
transects <- create_transects(shape_obj = map,
                             design = "systematic",
                             line.length = 400000,
                             design.angle = 2,
                             segmentize = TRUE,
                             length_segs = 2000)

# Plot
pal <- rep(c("#98C1D9","#EE6C4D","#293241"),nrow(transects)) 
ggplot() +
      geom_sf(data = map, color = "#D9D9D9") +
      geom_sf(data = transects, aes(colour = seg_ID))+
      scale_colour_manual(values = pal) +
      theme(legend.position = "none")

```

```{r tests-create_transects}
library(testthat)
library(dplyr)

test_that("create_transects works", {
  expect_true(inherits(create_transects, "function"))
})

test_that("test conformite create_transects", {

  data("shape_courseulles")
  
  set.seed(2022)
  
  map <- create_density_map(shape_obj = shape_courseulles,
                              N = 200,
                              grid_size = 1000,
                              density_type = "gradient",
                              gradient_direction = "N",
                              wavelength = 20000,
                              amplitude = 500)
  

  test_1 <- create_transects(shape_obj = shape_courseulles,
                             design = "systematic",
                             line.length = 400000,
                             design.angle = 2) %>%
    slice(1:5)
  
  test_2 <- create_transects(shape_obj = map,
                             design = "systematic",
                             line.length = 400000,
                             design.angle = 2,
                             segmentize = TRUE,
                             length_segs = 2000) %>%
    slice(1:5)

  exp_1 <- structure(list(transect = 1:5, seg_ID = 1:5, geometry = structure(list(
    structure(c(394055.793731328, 394710.958334824, 6936392.0721311, 
    6955153.53165881), .Dim = c(2L, 2L), class = c("XY", "LINESTRING", 
    "sfg")), structure(c(401360.757117791, 402360.769378203, 
    6926116.13476568, 6954752.73914086), .Dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(409128.031513907, 410010.580421582, 
    6929079.05256815, 6954351.9466229), .Dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(416717.132536868, 417660.391464961, 
    6926939.75252869, 6953951.15410494), .Dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(424270.340716261, 425310.20250834, 
    6923772.61592977, 6953550.36158698), .Dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg"))), class = c("sfc_LINESTRING", "sfc"
), precision = 0, bbox = structure(c(xmin = 394055.793731328, 
ymin = 6923772.61592977, xmax = 425310.20250834, ymax = 6955153.53165881
), class = "bbox"), crs = structure(list(input = "EPSG:2154", 
    wkt = "PROJCRS[\"RGF93 / Lambert-93\",\n    BASEGEOGCRS[\"RGF93\",\n        DATUM[\"Reseau Geodesique Francais 1993\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4171]],\n    CONVERSION[\"Lambert-93\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",46.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",3,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",49,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",44,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",700000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",6600000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"unknown\"],\n        AREA[\"France\"],\n        BBOX[41.15,-9.86,51.56,10.38]],\n    ID[\"EPSG\",2154]]"), class = "crs"), n_empty = 0L)), row.names = c(NA, 
-5L), class = c("sf", "data.frame"), sf_column = "geometry", agr = structure(c(transect = NA_integer_, 
seg_ID = NA_integer_), class = "factor", .Label = c("constant", 
"aggregate", "identity")))
  
  
  exp_2 <- structure(list(transect = c(1L, 1L, 1L, 1L, 1L), effort = structure(c(1876.14289556029, 
1876.14289556029, 1876.14289556029, 1876.14289556029, 1876.14289556122
), units = structure(list(numerator = "m", denominator = character(0)), class = "symbolic_units"), class = "units"), 
    seg_ID = c("1-1", "1-2", "1-3", "1-4", "1-5"), geometry = structure(list(
        structure(c(393461.469060267, 393526.945503064, 6938158.74575047, 
        6940033.74575047), .Dim = c(2L, 2L), class = c("XY", 
        "LINESTRING", "sfg")), structure(c(393526.945503064, 
        393592.421945861, 6940033.74575047, 6941908.74575047), .Dim = c(2L, 
        2L), class = c("XY", "LINESTRING", "sfg")), structure(c(393592.421945861, 
        393657.898388658, 6941908.74575047, 6943783.74575047), .Dim = c(2L, 
        2L), class = c("XY", "LINESTRING", "sfg")), structure(c(393657.898388658, 
        393723.374831455, 6943783.74575047, 6945658.74575047), .Dim = c(2L, 
        2L), class = c("XY", "LINESTRING", "sfg")), structure(c(393723.374831455, 
        393788.851274252, 6945658.74575047, 6947533.74575047), .Dim = c(2L, 
        2L), class = c("XY", "LINESTRING", "sfg"))), class = c("sfc_LINESTRING", 
    "sfc"), precision = 0, bbox = structure(c(xmin = 393461.469060267, 
    ymin = 6938158.74575047, xmax = 393788.851274252, ymax = 6947533.74575047
    ), class = "bbox"), crs = structure(list(input = "EPSG:2154", 
        wkt = "PROJCRS[\"RGF93 / Lambert-93\",\n    BASEGEOGCRS[\"RGF93\",\n        DATUM[\"Reseau Geodesique Francais 1993\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4171]],\n    CONVERSION[\"Lambert-93\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",46.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",3,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",49,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",44,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",700000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",6600000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"unknown\"],\n        AREA[\"France\"],\n        BBOX[41.15,-9.86,51.56,10.38]],\n    ID[\"EPSG\",2154]]"), class = "crs"), n_empty = 0L)), row.names = c("1", 
"1.1", "1.2", "1.3", "1.4"), class = c("sf", "data.frame"), sf_column = "geometry", agr = structure(c(transect = NA_integer_, 
effort = NA_integer_, seg_ID = NA_integer_), class = "factor", .Label = c("constant", 
"aggregate", "identity")))

expect_equal(object = test_1,
             expected = exp_1)

expect_equal(object = test_2,
             expected = exp_2)

expect_is(test_1, "data.frame")
expect_is(test_2, "data.frame")

})

test_that("test erreur create_transects", {
  
  data(iris)
  
  expect_error(object = create_transects(shape_obj = map,
                                         design = "hoho",
                                         line.length = 400000,
                                         design.angle = 2,
                                         segmentize = TRUE,
                                         length_segs = 2000))
  
  expect_error(object = create_transects(shape_obj = iris,
                                         design = "systematic",
                                         line.length = 400000))
  
  expect_error(object = create_transects(shape_obj = map,
                                         design = "systematic",
                                         line.length = "nop"))
  
  expect_error(object = create_transects(shape_obj = map,
                                         design = "systematic",
                                         line.length = 400000,
                                         design.angle = "haha"))
  
  expect_error(object = create_transects(shape_obj = map,
                                         design = "systematic",
                                         line.length = 400000,
                                         design.angle = 0,
                                         segmentize = TRUE,
                                         length_segs = "hehe"))
})

```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_sampling_design_emulator.Rmd", 
               vignette_name = "Sampling Design Emulator",
               open_vignette = FALSE,
               check = FALSE,
               overwrite = TRUE)
```
