---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

# My function

```{r function-create_density_map}


#' Create a map with the desired density of individuals
#'
#' @param shape_obj sf object. The shape of the study site.
#' @param N Numeric. The number of individuals desired in the area.
#' @param grid_size Numeric. Grid size in m.
#' @param density_type Character. 'uniform", 'gradient', 'random', 'covariate'.
#' @param gradient_direction Character. Only for "gradient" `density_type`. Where the highest density comes from. 'N','NE','E'...
#' @param wavelength Numeric. Only for "gradient" and "random" `density_type`. Wavelength of the hotspots of density created. Maximum wavelength for "random" `density_type`. 
#' @param amplitude Numeric. Only for "gradient" and "random" `density_type`. Amplitude of the hotspots of density created. Maximum amplitude for "random" `density_type`. 
#' @param nb_hotspots Numeric. Only for "random" `density_type`. Number of random hotspots to be created.
#'
#' @importFrom sf st_area st_sfc st_contains as_Spatial st_point st_sf st_transform
#' @importFrom sp bbox
#' @importFrom dssd make.region
#' @importFrom dsims make.density add.hotspot
#' @importFrom dplyr mutate filter select
#' @importFrom units drop_units
#' @importFrom stats runif
#' @importFrom assertthat assert_that
#'
#' @return sf object. The map with the densities type choosen and corresponding to the number of individuals desired in the study area. 
#' @export

create_density_map <- function(shape_obj, N, grid_size, density_type, gradient_direction, wavelength, amplitude, nb_hotspots) {
  
  shape_obj <- shape_obj %>%
    st_transform(crs = 2154)
  
  xlim <- bbox(as_Spatial(shape_obj))[1, ]
  ylim <- bbox(as_Spatial(shape_obj))[2, ]
  
  
  region_obj <- make.region(region.name = "Study site",
                            shape = shape_obj,
                            units = "m")
  
  if(density_type == "uniform"){ 
    
    density_obj <- make.density(region = region_obj,
                                x.space = grid_size,
                                y.space = grid_size,
                                constant = 1)
    
  }
  
  
  if(density_type == "gradient"){
    
    if(gradient_direction == "N") {          
      x <- mean(xlim)  
      y <- max(ylim) + (max(ylim) - min(ylim))
    }
    if(gradient_direction == "NE") {
      x <- max(xlim)  
      y <- max(ylim)
    }
    
    if(gradient_direction == "E"){
      x <- max(xlim) + (max(xlim) - min(xlim))  
      y <- mean(ylim)
    }
    
    if(gradient_direction == "SE"){
      x <- max(xlim) 
      y <- min(ylim)
    }
    
    if(gradient_direction == "S") {
      x <- mean(xlim)  
      y <- min(ylim) - (max(ylim) - min(ylim)) 
    }
    
    if(gradient_direction == "SW"){
      x <- min(xlim)  
      y <- min(ylim)
    }
    
    if(gradient_direction == "W"){
      x <- min(xlim) - (max(xlim) - min(xlim))  
      y <- mean(ylim) 
    }
    
    if(gradient_direction == "NW"){
      x <- min(xlim)
      y <- max(ylim)
    }
    
    density_obj <- make.density(region = region_obj,
                                x.space = grid_size,
                                y.space = grid_size,
                                constant = 1)
    
    density_obj <- add.hotspot(object = density_obj,
                               centre = c(x, y),
                               sigma = wavelength,
                               amplitude = amplitude)
    
  }
  

    if(density_type == "random"){
      
          density_obj <- make.density(region = region_obj,
                                x.space = grid_size,
                                y.space = grid_size,
                                constant = 1)
          
          for(i in 1:nb_hotspots){
            
            sigma_n <- runif(1, 1, wavelength)
            amplitude_n <- runif(1, 1, amplitude)
            
            x <- runif(1, xlim[1], xlim[2])
            y <- runif(1, ylim[1], ylim[2])
            
            point <- st_sfc(st_point(c(x,y)), crs = 2154)
            a <- as.numeric(st_contains(shape_obj, point))
            
            while(is.na(a==1)){
              
              x <- runif(1, xlim[1], xlim[2])
              y <- runif(1, ylim[1], ylim[2])
              
              point <- st_sfc(st_point(c(x,y)), crs = 2154)
              
              a <- as.numeric(st_contains(shape_obj, point))
            }
            
            density_obj <- add.hotspot(object = density_obj,
                                       centre = c(x, y),
                                       sigma = sigma_n,
                                       amplitude = amplitude_n)
            
            rm(a, x, y, sigma_n, amplitude_n)
            
          }
    }
      

    
  if(density_type == "covariate") {
    
    density_obj <- make.density(region = region_obj,
                                x.space = grid_size,
                                y.space = grid_size,
                                constant = 1)
  }
  
  
  map_obj <- density_obj@density.surface %>%
    as.data.frame() %>%
    st_sf(crs = 2154) %>%
    mutate(area = st_area(.)) %>%
    mutate(area_grid = grid_size^2) %>%
    drop_units() %>%
    filter(area == area_grid)
  
  total_area <- sum(map_obj$area)
  average_density <- N / total_area

  map_obj <- map_obj %>%
    mutate(density = average_density * density / mean(density, na.rm = TRUE)) %>%
    select(x,y,density,area,geometry)
        
}

```

```{r examples-create_density_map}

```

```{r tests-create_density_map}

```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console gradient_directionectly
fusen::inflate(flat_file = "dev/flat_population_abundance_emulator.Rmd", 
               vignette_name = "Population Abundance Emulator",
               open_vignette = FALSE,
               check = FALSE,
               overwrite = TRUE)
```
