# Generated by fusen: do not edit by hand

library(testthat)
library(dplyr)


test_that("simulate_ind works", {
  expect_true(inherits(simulate_ind, "function")) 
})


test_that("test conformite simulate_ind", {
  
  data("shape_courseulles")
  
  set.seed(2022)
  
  # First, create a density map
  map <- simulate_density(shape_obj = shape_courseulles,
                            density_type = "gradient",
                            gradient_direction = "N",
                            wavelength = 20000,
                            amplitude = 500)
  
  test <- simulate_ind(map_obj = map, N = 500) %>%
                 slice(1:5)

exp <- structure(list(x = c(432098.238355977, 420533.286240681, 434527.738948383, 
411815.477216414, 470612.945042581), y = c(6952762.23628262, 
6944532.6011364, 6950771.26691599, 6944138.62147687, 6945281.02163264
), size = c(1, 1, 1, 1, 1)), class = "data.frame", row.names = c(NA, 
-5L))

  expect_equal(object = test,
               expected = exp)

  expect_is(test, "data.frame")

})

test_that("test erreur simulate ind", {
  
  data(iris)
  
  expect_error(object = simulate_ind(map_obj = iris, N = 500))
  
  # First, create a density map
  map <- simulate_density(shape_obj = shape_courseulles,
                            density_type = "gradient",
                            gradient_direction = "N",
                            wavelength = 20000,
                            amplitude = 500)
  
  expect_error(object = simulate_ind(map_obj = map, N = "haha"))
  expect_error(object = simulate_ind(map_obj = map))

  
  map_test <- map %>%
    rename(nop = density)
  
  expect_error(object = simulate_ind(map_obj = map_test,N = 500))
  
  map_test <- map
  map_test$density[5] <- "nop"
  
  expect_error(object = simulate_ind(map_obj = map_test, N = 500))
  
  expect_error(object = simulate_ind(map_obj = map,
                                     N = 500,
                                     crs = "nop"))
  
})

