# Generated by fusen: do not edit by hand

library(testthat)
library(dplyr)


test_that("create_obs works", {
  expect_true(inherits(create_obs, "function")) 
})


test_that("test conformite create_obs", {
  
  data("shape_courseulles")
  
  set.seed(2022)
  
  # First, create a density map
  map <- create_density_map(shape_obj = shape_courseulles,
                            N = 1000,
                            density_type = "gradient",
                            gradient_direction = "N",
                            wavelength = 20000,
                            amplitude = 500)
  # Simulate ind
  ind <- simulate_ind(map_obj = map)
  
  # Then create transects
  transects <- create_transects(shape_obj = map,
                               design = "systematic",
                               line.length = 400000,
                               design.angle = 2,
                               segmentize = TRUE,
                               length_segs = 2000)
  
  
  
  test_1 <- create_obs(ind_obj = ind,
                      transect_obj = transects,
                      key = "hn",
                      g_zero = 1,
                      esw = 180) %>%
    slice(1:5)
  
  
  test_2 <- create_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 1,
                       truncation = 200) %>%
    slice(1:5)
  
  test_3 <- create_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "hn",
                       g_zero = 0.8,
                       esw = 180) %>%
    slice(1:5)
  
  
  test_4 <- create_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 0.6,
                       truncation = 300) %>%
    slice(1:5)
  
  
  exp_1 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0L, 
0L, 0L, 0L, 0L), proba = c(1.85303850324837e-20, 1.094571120915e-56, 
6.89602678224973e-69, 2.94160921470329e-113, 8.3114181204342e-62
), distance = c(1369.0592183218, 2305.56406914338, 2544.51293629123, 
3269.43192253455, 2408.7186646873), seg_ID = c("6-15", "5-10", 
"7-15", "3-8", "12-16"), x = c(431775.072857303, 420574.950567477, 
434997.642150412, 411643.817603619, 471141.824978667), y = c(6953113.82923826, 
6944770.46572502, 6950439.73189654, 6943461.32505072, 6946109.31119641
)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_2 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0, 
0, 0, 0, 0), proba = c(0, 0, 0, 0, 0), distance = c(1369.0592183218, 
2305.56406914338, 2544.51293629123, 3269.43192253455, 2408.7186646873
), seg_ID = c("6-15", "5-10", "7-15", "3-8", "12-16"), x = c(431775.072857303, 
420574.950567477, 434997.642150412, 411643.817603619, 471141.824978667
), y = c(6953113.82923826, 6944770.46572502, 6950439.73189654, 
6943461.32505072, 6946109.31119641)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_3 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0L, 
0L, 0L, 0L, 0L), proba = c(1.4824308025987e-20, 8.75656896732001e-57, 
5.51682142579978e-69, 2.35328737176263e-113, 6.64913449634736e-62
), distance = c(1369.0592183218, 2305.56406914338, 2544.51293629123, 
3269.43192253455, 2408.7186646873), seg_ID = c("6-15", "5-10", 
"7-15", "3-8", "12-16"), x = c(431775.072857303, 420574.950567477, 
434997.642150412, 411643.817603619, 471141.824978667), y = c(6953113.82923826, 
6944770.46572502, 6950439.73189654, 6943461.32505072, 6946109.31119641
)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_4 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0, 
0, 0, 0, 0), proba = c(0, 0, 0, 0, 0), distance = c(1369.0592183218, 
2305.56406914338, 2544.51293629123, 3269.43192253455, 2408.7186646873
), seg_ID = c("6-15", "5-10", "7-15", "3-8", "12-16"), x = c(431775.072857303, 
420574.950567477, 434997.642150412, 411643.817603619, 471141.824978667
), y = c(6953113.82923826, 6944770.46572502, 6950439.73189654, 
6943461.32505072, 6946109.31119641)), row.names = c(NA, -5L), class = "data.frame")
    
    
expect_equal(object = test_1,
             expected = exp_1)

expect_equal(object = test_2,
             expected = exp_2)

expect_equal(object = test_3,
             expected = exp_3)

expect_equal(object = test_4,
             expected = exp_4)

expect_is(test_1, "data.frame")
expect_is(test_2, "data.frame")
expect_is(test_3, "data.frame")
expect_is(test_4, "data.frame")

})

test_that("test erreur create_obs", {
  


  expect_error(object = create_obs(ind_obj = c(1,1,2),
                       transect_obj = transects,
                       key = "hn",
                       g_zero = 1,
                       esw = 180))
  
  expect_error(object = create_obs(ind_obj = ind,
                       transect_obj = c(1,1,2),
                       key = "hn",
                       g_zero = 1,
                       esw = 180))
  
  expect_error(object = create_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "hn",
                       esw = '180'))
  
  expect_error(object = create_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 1,
                       truncation = '180'))
  
})

library(testthat)

test_that("scale_hn works", {
  expect_true(inherits(scale_hn, "function")) 
})


test_that("test conformite scale_hn", {
  
  expect_equal(round(scale_hn(esw = 0.16), digits=3),
               expected = 0.128)
  
  expect_is(scale_hn(esw = 0.16), "numeric")
  
})

test_that("test erreur scale_hn", {
  
  expect_error(object = scale_hn(esw = "haha"))
  
})

library(testthat)

test_that("esw_hn works", {
  expect_true(inherits(esw_hn, "function")) 
})


test_that("test conformite esw_hn", {
  
  expect_equal(round(esw_hn(sigma = 0.3), digits = 3),
               expected = 0.376)
  
  expect_is(esw_hn(sigma = 0.3), "numeric")
  
})

test_that("test erreur esw_hn", {
  
  expect_error(object = esw_hn(sigma = "haha"))
  
})
