# WARNING - Generated by {fusen} from /dev/flat_observation_data_emulator.Rmd: do not edit by hand

library(testthat)
library(dplyr)


test_that("simulate_obs works", {
  expect_true(inherits(simulate_obs, "function")) 
})


test_that("test conformite simulate_obs", {
  
  data("shape_courseulles")
  
  set.seed(2022)
  
  # First, create a density map
  map <- simulate_density(shape_obj = shape_courseulles,
                            density_type = "gradient",
                            gradient_direction = "N",
                            wavelength = 20000,
                            amplitude = 500)
  # Simulate ind
  ind <- simulate_ind(map_obj = map, N = 500)
  
  # Then create transects
  transects <- simulate_transects(shape_obj = map,
                               design = "systematic",
                               line_length = 400000,
                               design_angle = 2,
                               segmentize = TRUE,
                               seg_length = 2000)
  
  
  
  test_1 <- simulate_obs(ind_obj = ind,
                      transect_obj = transects,
                      key = "hn",
                      g_zero = 1,
                      esw = 180) %>%
    slice(1:5)
  
  
  test_2 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 1,
                       truncation = 200) %>%
    slice(1:5)
  
  test_3 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "hn",
                       g_zero = 0.8,
                       esw = 180) %>%
    slice(1:5)
  
  
  test_4 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 0.6,
                       truncation = 300) %>%
    slice(1:5)
  
  
  exp_1 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0L, 
0L, 0L, 0L, 0L), proba = c(5.62629724409074e-82, 3.9164129155712e-59, 
9.26482554786274e-84, 0.0410598745944508, 7.22650051315455e-20
), distance = c(2778.09119808211, 2355.41953884001, 2808.41445102558, 
362.917781622493, 1348.39935709469), seg_ID = c("5-10", "8-13", 
"3-8", "12-4", "6-12"), x = c(420735.085058459, 442929.50649375, 
411813.427786551, 473010.809885187, 429456.966987101), y = c(6944722.05314103, 
6946677.08270922, 6943497.73469272, 6922335.09657975, 6946351.78889112
)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_2 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0, 
0, 0, 0, 0), proba = c(0, 0, 0, 0, 0), distance = c(2778.09119808211, 
2355.41953884001, 2808.41445102558, 362.917781622493, 1348.39935709469
), seg_ID = c("5-10", "8-13", "3-8", "12-4", "6-12"), x = c(420735.085058459, 
442929.50649375, 411813.427786551, 473010.809885187, 429456.966987101
), y = c(6944722.05314103, 6946677.08270922, 6943497.73469272, 
6922335.09657975, 6946351.78889112)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_3 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0L, 
0L, 0L, 0L, 0L), proba = c(4.50103779527259e-82, 3.13313033245696e-59, 
7.41186043829019e-84, 0.0328478996755607, 5.78120041052364e-20
), distance = c(2778.09119808211, 2355.41953884001, 2808.41445102558, 
362.917781622493, 1348.39935709469), seg_ID = c("5-10", "8-13", 
"3-8", "12-4", "6-12"), x = c(420735.085058459, 442929.50649375, 
411813.427786551, 473010.809885187, 429456.966987101), y = c(6944722.05314103, 
6946677.08270922, 6943497.73469272, 6922335.09657975, 6946351.78889112
)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_4 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0, 
0, 0, 0, 0), proba = c(0, 0, 0, 0, 0), distance = c(2778.09119808211, 
2355.41953884001, 2808.41445102558, 362.917781622493, 1348.39935709469
), seg_ID = c("5-10", "8-13", "3-8", "12-4", "6-12"), x = c(420735.085058459, 
442929.50649375, 411813.427786551, 473010.809885187, 429456.966987101
), y = c(6944722.05314103, 6946677.08270922, 6943497.73469272, 
6922335.09657975, 6946351.78889112)), row.names = c(NA, -5L), class = "data.frame")
    
    
expect_equal(object = test_1,
             expected = exp_1)

expect_equal(object = test_2,
             expected = exp_2)

expect_equal(object = test_3,
             expected = exp_3)

expect_equal(object = test_4,
             expected = exp_4)

expect_is(test_1, "data.frame")
expect_is(test_2, "data.frame")
expect_is(test_3, "data.frame")
expect_is(test_4, "data.frame")

})

test_that("test erreur simulate_obs", {
  


  expect_error(object = simulate_obs(ind_obj = c(1,1,2),
                       transect_obj = transects,
                       key = "hn",
                       g_zero = 1,
                       esw = 180))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = c(1,1,2),
                       key = "hn",
                       g_zero = 1,
                       esw = 180))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "hn",
                       esw = '180'))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 1,
                       truncation = '180'))
  
})

library(testthat)

test_that("scale_hn works", {
  expect_true(inherits(scale_hn, "function")) 
})


test_that("test conformite scale_hn", {
  
  expect_equal(round(scale_hn(esw = 0.16), digits=3),
               expected = 0.128)
  
  expect_is(scale_hn(esw = 0.16), "numeric")
  
})

test_that("test erreur scale_hn", {
  
  expect_error(object = scale_hn(esw = "haha"))
  
})

library(testthat)

test_that("esw_hn works", {
  expect_true(inherits(esw_hn, "function")) 
})


test_that("test conformite esw_hn", {
  
  expect_equal(round(esw_hn(sigma = 0.3), digits = 3),
               expected = 0.376)
  
  expect_is(esw_hn(sigma = 0.3), "numeric")
  
})

test_that("test erreur esw_hn", {
  
  expect_error(object = esw_hn(sigma = "haha"))
  
})
