# WARNING - Generated by {fusen} from /dev/flat_sampling_design_emulator.Rmd: do not edit by hand

library(testthat)
library(dplyr)

test_that("simulate_transects works", {
  expect_true(inherits(simulate_transects, "function"))
})

test_that("test conformite simulate_transects", {

  data("shape_courseulles")
  
  set.seed(2022)
  
  map <- simulate_density(shape_obj = shape_courseulles,
                              grid_size = 1000,
                              density_type = "gradient",
                              gradient_direction = "N",
                              wavelength = 20000,
                              amplitude = 500)
  

  test_1 <- simulate_transects(shape_obj = shape_courseulles,
                             design = "systematic",
                             line_length = 400000,
                             design_angle = 2) %>%
    slice(1:5)
  
  test_2 <- simulate_transects(shape_obj = map,
                             design = "systematic",
                             line_length = 400000,
                             design_angle = 2,
                             segmentize = TRUE,
                             seg_length = 2000) %>%
    slice(1:5)

  exp_1 <- structure(list(transect = 1:5, seg_ID = 1:5, effort = structure(c(18772.895468405, 
28654.059654105, 25288.2990032283, 27027.8662220783, 29795.8965123036
), units = structure(list(numerator = "m", denominator = character(0)), class = "symbolic_units"), class = "units"), 
    geometry = structure(list(structure(c(394055.793731328, 394710.958334824, 
    6936392.0721311, 6955153.53165881), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(401360.757117791, 402360.769378203, 
    6926116.13476568, 6954752.73914085), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(409128.031513907, 410010.580421582, 
    6929079.05256815, 6954351.9466229), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(416717.132536868, 417660.391464961, 
    6926939.75252869, 6953951.15410494), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(424270.340716261, 425310.20250834, 
    6923772.61592977, 6953550.36158698), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg"))), class = c("sfc_LINESTRING", "sfc"
    ), precision = 0, bbox = structure(c(xmin = 394055.793731328, 
    ymin = 6923772.61592977, xmax = 425310.20250834, ymax = 6955153.53165881
    ), class = "bbox"), crs = structure(list(input = "EPSG:2154", 
        wkt = "PROJCRS[\"RGF93 / Lambert-93\",\n    BASEGEOGCRS[\"RGF93\",\n        DATUM[\"Reseau Geodesique Francais 1993\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4171]],\n    CONVERSION[\"Lambert-93\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",46.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",3,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",49,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",44,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",700000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",6600000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"France - onshore and offshore, mainland and Corsica.\"],\n        BBOX[41.15,-9.86,51.56,10.38]],\n    ID[\"EPSG\",2154]]"), class = "crs"), n_empty = 0L)), row.names = c(NA, 
-5L), class = c("sf", "data.frame"), sf_column = "geometry", agr = structure(c(transect = NA_integer_, 
seg_ID = NA_integer_, effort = NA_integer_), class = "factor", levels = c("constant", 
"aggregate", "identity")))
  
  
  exp_2 <- structure(list(transect = c(1L, 1L, 1L, 1L, 1L), seg_ID = c("1-1", 
"1-2", "1-3", "1-4", "1-5"), effort = structure(c(1876.14289556029, 
1876.14289556029, 1876.14289556029, 1876.14289556029, 1876.14289556122
), units = structure(list(numerator = "m", denominator = character(0)), class = "symbolic_units"), class = "units"), 
    geometry = structure(list(structure(c(393461.469060267, 393526.945503064, 
    6938158.74575047, 6940033.74575047), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(393526.945503064, 393592.421945861, 
    6940033.74575047, 6941908.74575047), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(393592.421945861, 393657.898388658, 
    6941908.74575047, 6943783.74575047), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(393657.898388658, 393723.374831455, 
    6943783.74575047, 6945658.74575047), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg")), structure(c(393723.374831455, 393788.851274252, 
    6945658.74575047, 6947533.74575047), dim = c(2L, 2L), class = c("XY", 
    "LINESTRING", "sfg"))), class = c("sfc_LINESTRING", "sfc"
    ), precision = 0, bbox = structure(c(xmin = 393461.469060267, 
    ymin = 6938158.74575047, xmax = 393788.851274252, ymax = 6947533.74575047
    ), class = "bbox"), crs = structure(list(input = "EPSG:2154", 
        wkt = "PROJCRS[\"RGF93 / Lambert-93\",\n    BASEGEOGCRS[\"RGF93\",\n        DATUM[\"Reseau Geodesique Francais 1993\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4171]],\n    CONVERSION[\"Lambert-93\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",46.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",3,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",49,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",44,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",700000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",6600000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"France - onshore and offshore, mainland and Corsica.\"],\n        BBOX[41.15,-9.86,51.56,10.38]],\n    ID[\"EPSG\",2154]]"), class = "crs"), n_empty = 0L)), row.names = c("1", 
"1.1", "1.2", "1.3", "1.4"), class = c("sf", "data.frame"), sf_column = "geometry", agr = structure(c(transect = NA_integer_, 
seg_ID = NA_integer_, effort = NA_integer_), class = "factor", levels = c("constant", 
"aggregate", "identity")))

expect_equal(object = test_1,
             expected = exp_1)

expect_equal(object = test_2,
             expected = exp_2)

expect_is(test_1, "data.frame")
expect_is(test_2, "data.frame")

})

test_that("test erreur simulate_transects", {
  
  data(iris)
  
  expect_error(object = simulate_transects(shape_obj = map,
                                         design = "hoho",
                                         line_length = 400000,
                                         design_angle = 2,
                                         segmentize = TRUE,
                                         seg_length = 2000))
    
  expect_error(object = simulate_transects(shape_obj = iris,
                                         design = "systematic",
                                         line_length = 400000))
  
  expect_error(object = simulate_transects(shape_obj = map,
                                         design = "systematic",
                                         line_length = "nop"))
  
  expect_error(object = simulate_transects(shape_obj = map,
                                         design = "systematic",
                                         line_length = 400000,
                                         design_angle = "haha"))
  
  expect_error(object = simulate_transects(shape_obj = map,
                                         design = "systematic",
                                         line_length = 400000,
                                         design_angle = 0,
                                         segmentize = TRUE,
                                         seg_length = "hehe"))
})

