# Generated by fusen: do not edit by hand

# library(dsims)
# library(dplyr)
# 
# test_that("create_transect works", {
#   expect_true(inherits(extract_map, "function")) 
# })
# 
# test_that("test conformite create_transects", {
#   
#   # Use of the St Andrews bay map from the dssd package
#   shapefile.name <- system.file("extdata", "StAndrew.shp", package = "dssd")
#   
#   # Creation of the object with the make.region function of the dsims package
#   region <- make.region(region.name = "St Andrews bay",
#                         shape = shapefile.name,
#                         units = "m")
#   
#   set.seed(2022)
#   
#   test <- region %>%
#     create_transect(crs = 2154,
#                     design = "eszigzag",
#                     line.length = 400000,
#                     design.angle = 30,
#                     truncation = 400) %>%
#     slice(1:5)
#   
#   exp <- structure(list(transect = 1:5, geometry = structure(list(structure(c(-141183.902141867, 
# -139500.764814892, 6280201.52483057, 6279087.12793825), .Dim = c(2L, 
# 2L), class = c("XY", "LINESTRING", "sfg")), structure(c(-139580.553918026, 
# -147097.394879464, 6276674.72174561, 6280421.11344795), .Dim = c(2L, 
# 2L), class = c("XY", "LINESTRING", "sfg")), structure(c(-150698.57878731, 
# -139693.221386756, 6280554.83797088, 6273268.24531468), .Dim = c(2L, 
# 2L), class = c("XY", "LINESTRING", "sfg")), structure(c(-139760.806627915, 
# -153594.133992233, 6271224.82023657, 6278119.34722194), .Dim = c(2L, 
# 2L), class = c("XY", "LINESTRING", "sfg")), structure(c(-154474.999621736, 
# -139885.677958619, 6277108.88034423, 6267449.36269112), .Dim = c(2L, 
# 2L), class = c("XY", "LINESTRING", "sfg"))), class = c("sfc_LINESTRING", 
# "sfc"), precision = 0, bbox = structure(c(xmin = -154474.999621736, 
# ymin = 6267449.36269112, xmax = -139500.764814892, ymax = 6280554.83797088
# ), class = "bbox"), crs = structure(list(input = "EPSG:2154", 
#     wkt = "PROJCRS[\"RGF93 / Lambert-93\",\n    BASEGEOGCRS[\"RGF93\",\n        DATUM[\"Reseau Geodesique Francais 1993\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4171]],\n    CONVERSION[\"Lambert-93\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",46.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",3,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",49,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",44,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",700000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",6600000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"unknown\"],\n        AREA[\"France\"],\n        BBOX[41.15,-9.86,51.56,10.38]],\n    ID[\"EPSG\",2154]]"), class = "crs"), n_empty = 0L)), row.names = c(NA, 
# -5L), class = c("sf", "data.frame"), sf_column = "geometry", agr = structure(c(transect = NA_integer_), class = "factor", .Label = c("constant", 
# "aggregate", "identity")))
#   
#   expect_equal(object = test,
#                expected = exp)
#   
#   expect_is(test, "data.frame")
#   
# })
# 
# test_that("test erreur extract_map", {
#   
#   data(iris)
#   
#   expect_error(object = create_transect(crs = 2154,
#                                         design = "eszigzag",
#                                         line.length = 400000,
#                                         design.angle = 30,
#                                         truncation = 400))
#   
# })

