# Generated by fusen: do not edit by hand

library(testthat)
library(dplyr)

test_that("simulate_ind works", {
  expect_true(inherits(simulate_ind, "function")) 
})

test_that("test conformite simulate_ind", {
  
  data("shape_courseulles")
  
  set.seed(2022)
  
  # First, create a density map
  map <- simulate_density(shape_obj = shape_courseulles,
                            density_type = "gradient",
                            gradient_direction = "N",
                            wavelength = 20000,
                            amplitude = 500)
  
  test_1 <- simulate_ind(map_obj = map, N = 500) %>%
                 slice(1:5)
  
  test_2 <- simulate_ind(map_obj = map, N = 500, mean_group_size = 3) %>%
                 slice(1:5)

exp_1 <- structure(list(x = c(442098.238355977, 420533.286240681, 443527.738948383, 
411815.477216414, 470612.945042581), y = c(6926762.23628262, 
6944532.6011364, 6939771.26691599, 6944138.62147687, 6945281.02163264
), size = c(1, 1, 1, 1, 1)), class = "data.frame", row.names = c(NA, 
-5L))

exp_2 <- structure(list(x = c(472685.185622455, 438778.109058536, 437555.810525346, 
459633.647628858, 456106.671207615), y = c(6940978.15048733, 
6932096.386525, 6941737.78689435, 6950947.10736784, 6928151.73028891
), size = c(3, 5, 7, 3, 4)), class = "data.frame", row.names = c(NA, 
-5L))

  expect_equal(object = test_1,
               expected = exp_1)
  
  expect_equal(object = test_2,
               expected = exp_2)

  expect_is(test_1, "data.frame")
  expect_is(test_2, "data.frame")

})

test_that("test erreur simulate ind", {
  
  data(iris)
  
  expect_error(object = simulate_ind(map_obj = iris, N = 500))
  
  # First, create a density map
  map <- simulate_density(shape_obj = shape_courseulles,
                            density_type = "gradient",
                            gradient_direction = "N",
                            wavelength = 20000,
                            amplitude = 500)
  
  expect_error(object = simulate_ind(map_obj = map, N = "haha"))
  expect_error(object = simulate_ind(map_obj = map))

  
  map_test <- map %>%
    rename(nop = density)
  
  expect_error(object = simulate_ind(map_obj = map_test,N = 500))
  
  map_test <- map
  map_test$density[5] <- "nop"
  
  expect_error(object = simulate_ind(map_obj = map_test, N = 500))
    expect_error(object = simulate_ind(map_obj = map, N = 500, mean_group_size = "ahah"))

  expect_error(object = simulate_ind(map_obj = map,
                                     N = 500,
                                     crs = "nop"))
  
})

