# Generated by fusen: do not edit by hand

library(testthat)
library(dplyr)


test_that("simulate_obs works", {
  expect_true(inherits(simulate_obs, "function")) 
})


test_that("test conformite simulate_obs", {
  
  data("shape_courseulles")
  
  set.seed(2022)
  
  # First, create a density map
  map <- simulate_density(shape_obj = shape_courseulles,
                            density_type = "gradient",
                            gradient_direction = "N",
                            wavelength = 20000,
                            amplitude = 500)
  # Simulate ind
  ind <- simulate_ind(map_obj = map, N = 500)
  
  # Then create transects
  transects <- simulate_transects(shape_obj = map,
                               design = "systematic",
                               line.length = 400000,
                               design.angle = 2,
                               segmentize = TRUE,
                               length_segs = 2000)
  
  
  
  test_1 <- simulate_obs(ind_obj = ind,
                      transect_obj = transects,
                      key = "hn",
                      g_zero = 1,
                      esw = 180) %>%
    slice(1:5)
  
  
  test_2 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 1,
                       truncation = 200) %>%
    slice(1:5)
  
  test_3 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "hn",
                       g_zero = 0.8,
                       esw = 180) %>%
    slice(1:5)
  
  
  test_4 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 0.6,
                       truncation = 300) %>%
    slice(1:5)
  
  
  exp_1 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0L, 
0L, 1L, 0L, 0L), proba = c(5.57408603285241e-08, 4.66293367408908e-19, 
0.602629418799049, 1.00932158605189e-82, 2.70796644221945e-38
), distance = c(830.078156629012, 1319.57027537831, 144.543000948544, 
2790.81895410615, 1889.03814715369), seg_ID = c("8-3", "5-10", 
"8-9", "4-8", "12-16"), x = c(442098.238355977, 420533.286240681, 
443527.738948383, 411815.477216414, 470612.945042581), y = c(6926762.23628262, 
6944532.6011364, 6939771.26691599, 6944138.62147687, 6945281.02163264
)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_2 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0, 
0, 1, 0, 0), proba = c(0, 0, 1, 0, 0), distance = c(830.078156629012, 
1319.57027537831, 144.543000948544, 2790.81895410615, 1889.03814715369
), seg_ID = c("8-3", "5-10", "8-9", "4-8", "12-16"), x = c(442098.238355977, 
420533.286240681, 443527.738948383, 411815.477216414, 470612.945042581
), y = c(6926762.23628262, 6944532.6011364, 6939771.26691599, 
6944138.62147687, 6945281.02163264)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_3 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0L, 
0L, 1L, 0L, 0L), proba = c(4.45926882628192e-08, 3.73034693927126e-19, 
0.482103535039239, 8.0745726884151e-83, 2.16637315377556e-38), 
    distance = c(830.078156629012, 1319.57027537831, 144.543000948544, 
    2790.81895410615, 1889.03814715369), seg_ID = c("8-3", "5-10", 
    "8-9", "4-8", "12-16"), x = c(442098.238355977, 420533.286240681, 
    443527.738948383, 411815.477216414, 470612.945042581), y = c(6926762.23628262, 
    6944532.6011364, 6939771.26691599, 6944138.62147687, 6945281.02163264
    )), row.names = c(NA, -5L), class = "data.frame")
    
  exp_4 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0, 
0, 0, 0, 0), proba = c(0, 0, 0.6, 0, 0), distance = c(830.078156629012, 
1319.57027537831, 144.543000948544, 2790.81895410615, 1889.03814715369
), seg_ID = c("8-3", "5-10", "8-9", "4-8", "12-16"), x = c(442098.238355977, 
420533.286240681, 443527.738948383, 411815.477216414, 470612.945042581
), y = c(6926762.23628262, 6944532.6011364, 6939771.26691599, 
6944138.62147687, 6945281.02163264)), row.names = c(NA, -5L), class = "data.frame")
    
    
expect_equal(object = test_1,
             expected = exp_1)

expect_equal(object = test_2,
             expected = exp_2)

expect_equal(object = test_3,
             expected = exp_3)

expect_equal(object = test_4,
             expected = exp_4)

expect_is(test_1, "data.frame")
expect_is(test_2, "data.frame")
expect_is(test_3, "data.frame")
expect_is(test_4, "data.frame")

})

test_that("test erreur simulate_obs", {
  


  expect_error(object = simulate_obs(ind_obj = c(1,1,2),
                       transect_obj = transects,
                       key = "hn",
                       g_zero = 1,
                       esw = 180))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = c(1,1,2),
                       key = "hn",
                       g_zero = 1,
                       esw = 180))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "hn",
                       esw = '180'))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 1,
                       truncation = '180'))
  
})

library(testthat)

test_that("scale_hn works", {
  expect_true(inherits(scale_hn, "function")) 
})


test_that("test conformite scale_hn", {
  
  expect_equal(round(scale_hn(esw = 0.16), digits=3),
               expected = 0.128)
  
  expect_is(scale_hn(esw = 0.16), "numeric")
  
})

test_that("test erreur scale_hn", {
  
  expect_error(object = scale_hn(esw = "haha"))
  
})

library(testthat)

test_that("esw_hn works", {
  expect_true(inherits(esw_hn, "function")) 
})


test_that("test conformite esw_hn", {
  
  expect_equal(round(esw_hn(sigma = 0.3), digits = 3),
               expected = 0.376)
  
  expect_is(esw_hn(sigma = 0.3), "numeric")
  
})

test_that("test erreur esw_hn", {
  
  expect_error(object = esw_hn(sigma = "haha"))
  
})
