# WARNING - Generated by {fusen} from /dev/flat_observation_data_emulator.Rmd: do not edit by hand

library(testthat)
library(dplyr)


test_that("simulate_obs works", {
  expect_true(inherits(simulate_obs, "function")) 
})


test_that("test conformite simulate_obs", {
  
  data("shape_courseulles")
  
  set.seed(2022)
  
  # First, create a density map
  map <- simulate_density(shape_obj = shape_courseulles,
                            density_type = "gradient",
                            gradient_direction = "N",
                            wavelength = 20000,
                            amplitude = 500)
  # Simulate ind
  ind <- simulate_ind(map_obj = map, N = 500)
  
  # Then create transects
  transects <- simulate_transects(shape_obj = map,
                               design = "systematic",
                               line_length = 400000,
                               design_angle = 2,
                               segmentize = TRUE,
                               seg_length = 2000)
  
  
  
  test_1 <- simulate_obs(ind_obj = ind,
                      transect_obj = transects,
                      key = "hn",
                      g_zero = 1,
                      esw = 180) %>%
    slice(1:5)
  
  
  test_2 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 1,
                       truncation = 200) %>%
    slice(1:5)
  
  test_3 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "hn",
                       g_zero = 0.8,
                       esw = 180) %>%
    slice(1:5)
  
  
  test_4 <- simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 0.6,
                       truncation = 300) %>%
    slice(1:5)
  
  
  exp_1 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0L, 
0L, 0L, 0L, 0L), proba = c(2.38013147506207e-11, 7.92609305432881e-25, 
9.71703231869797e-05, 6.88956913101349e-91, 2.21863437480828e-104
), distance = c(1004.53981908493, 1513.04695908988, 617.363729121525, 
2926.48777737356, 3137.82170094333), seg_ID = c("5-10", "8-13", 
"4-8", "12-4", "6-12"), x = c(420661.308070772, 442923.262113165, 
411757.519017249, 472449.639991486, 430079.183413966), y = c(6944991.45049146, 
6946420.8560698, 6943660.15443901, 6922780.12565343, 6946391.36611633
)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_2 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0, 
0, 0, 0, 0), proba = c(0, 0, 0, 0, 0), distance = c(1004.53981908493, 
1513.04695908988, 617.363729121525, 2926.48777737356, 3137.82170094333
), seg_ID = c("5-10", "8-13", "4-8", "12-4", "6-12"), x = c(420661.308070772, 
442923.262113165, 411757.519017249, 472449.639991486, 430079.183413966
), y = c(6944991.45049146, 6946420.8560698, 6943660.15443901, 
6922780.12565343, 6946391.36611633)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_3 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0L, 
0L, 0L, 0L, 0L), proba = c(1.90410518004965e-11, 6.34087444346305e-25, 
7.77362585495838e-05, 5.5116553048108e-91, 1.77490749984662e-104
), distance = c(1004.53981908493, 1513.04695908988, 617.363729121525, 
2926.48777737356, 3137.82170094333), seg_ID = c("5-10", "8-13", 
"4-8", "12-4", "6-12"), x = c(420661.308070772, 442923.262113165, 
411757.519017249, 472449.639991486, 430079.183413966), y = c(6944991.45049146, 
6946420.8560698, 6943660.15443901, 6922780.12565343, 6946391.36611633
)), row.names = c(NA, -5L), class = "data.frame")
    
  exp_4 <- structure(list(object_ID = 1:5, size = c(1, 1, 1, 1, 1), detected = c(0, 
0, 0, 0, 0), proba = c(0, 0, 0, 0, 0), distance = c(1004.53981908493, 
1513.04695908988, 617.363729121525, 2926.48777737356, 3137.82170094333
), seg_ID = c("5-10", "8-13", "4-8", "12-4", "6-12"), x = c(420661.308070772, 
442923.262113165, 411757.519017249, 472449.639991486, 430079.183413966
), y = c(6944991.45049146, 6946420.8560698, 6943660.15443901, 
6922780.12565343, 6946391.36611633)), row.names = c(NA, -5L), class = "data.frame")
    
    
expect_equal(object = test_1,
             expected = exp_1)

expect_equal(object = test_2,
             expected = exp_2)

expect_equal(object = test_3,
             expected = exp_3)

expect_equal(object = test_4,
             expected = exp_4)

expect_is(test_1, "data.frame")
expect_is(test_2, "data.frame")
expect_is(test_3, "data.frame")
expect_is(test_4, "data.frame")

})

test_that("test erreur simulate_obs", {
  


  expect_error(object = simulate_obs(ind_obj = c(1,1,2),
                       transect_obj = transects,
                       key = "hn",
                       g_zero = 1,
                       esw = 180))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = c(1,1,2),
                       key = "hn",
                       g_zero = 1,
                       esw = 180))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "hn",
                       esw = '180'))
  
  expect_error(object = simulate_obs(ind_obj = ind,
                       transect_obj = transects,
                       key = "unif",
                       g_zero = 1,
                       truncation = '180'))
  
})

library(testthat)

test_that("scale_hn works", {
  expect_true(inherits(scale_hn, "function")) 
})


test_that("test conformite scale_hn", {
  
  expect_equal(round(scale_hn(esw = 0.16), digits=3),
               expected = 0.128)
  
  expect_is(scale_hn(esw = 0.16), "numeric")
  
})

test_that("test erreur scale_hn", {
  
  expect_error(object = scale_hn(esw = "haha"))
  
})

library(testthat)

test_that("esw_hn works", {
  expect_true(inherits(esw_hn, "function")) 
})


test_that("test conformite esw_hn", {
  
  expect_equal(round(esw_hn(sigma = 0.3), digits = 3),
               expected = 0.376)
  
  expect_is(esw_hn(sigma = 0.3), "numeric")
  
})

test_that("test erreur esw_hn", {
  
  expect_error(object = esw_hn(sigma = "haha"))
  
})
