# WARNING - Generated by {fusen} from /dev/flat_population_abundance_emulator.Rmd: do not edit by hand


#' Simulate individuals
#'
#' @description
#' `simulate_ind` allows to simulate a approximate number of individuals with a inhomogenous Poisson point process according to the densities provided.
#'
#' @details
#' This function need a grid sf object with density assosciated to each square of the grid.
#' For each simulated individuals, a size is associated. Thus, it is possible to simulate group. Group are simulated using a Poisson distribution, with parameter `mean_group_size`. By default size is 1.
#'
#' @param map_obj sf dataframe. Sf map with a colum containg density informations
#' @param N numeric. The number of individuals desired in the area.
#' @param mean_group_size numeric. Mean size of groups to simulate. By default = 1.
#' @param crs numeric. Projection system. By default: 2154. 
#'
#' @importFrom glue glue
#' @importFrom assertthat assert_that
#' @importFrom stats rpois
#' @importFrom dplyr mutate select filter
#' @importFrom sf st_centroid st_coordinates st_crs st_area
#' @importFrom spatstat.random rpoispp
#' @importFrom spatstat.geom as.im
#'
#' @return The simulated individuals in a dataframe. The dataframe contains three columns, `x` longitude of the simulated individual, `y` latitude of the simulated individual and `size` the number of individuals simulated on the location (the possibility of simulate groupe will comming).  
#' @export

#' @examples
#' 
#' library(ggplot2)
#' data("shape_courseulles")
#' 
#' # First, create a map with a gradient density from the North
#' map <- simulate_density(shape_obj = shape_courseulles,
#'                               grid_size = 1000,
#'                               density_type = "gradient",
#'                               gradient_direction = "N",
#'                               wavelength = 20000,
#'                               amplitude = 15)
#' 
#' # ------------------------------
#' # Example 1. Simulate the presence of 200 individuals 
#' # ------------------------------
#' 
#' ind <- simulate_ind(map_obj = map, N = 200)
#' 
#' # Plot
#' ggplot() +
#'   geom_sf(data = map, aes(fill = density)) +
#'   geom_point(data = ind, aes(x = x, y = y)) +
#'   theme(panel.background = element_rect(fill = "white"),
#'         panel.grid.major = element_line(colour = "#EDEDE9"))
#' 
#' 
#' # ------------------------------
#' # Example 2. Simulate the presence of 100 groups with a mean group size of 5 individuals 
#' # ------------------------------
#' 
#' ind <- simulate_ind(map_obj = map, mean_group_size = 5, N = 100)
#' 
#' # Plot
#' ggplot() +
#'   geom_sf(data = map) +
#'   geom_point(data = ind, aes(x = x, y = y, color = size)) +
#'   theme(panel.background = element_rect(fill = "white"),
#'         panel.grid.major = element_line(colour = "#EDEDE9"))
#'   
simulate_ind <- function(map_obj, N, mean_group_size = 1, crs = 2154) {
  
  # Function checks
  assert_that(inherits(map_obj, "sf"))
  if (!all(c("density") %in% names(map_obj))) {stop("map_obj must contain `density` column. Verify your column names.")}
  assert_that(is.numeric(map_obj$density))
  assert_that(is.numeric(crs))
  assert_that(is.numeric(N))
  assert_that(is.numeric(mean_group_size))

  
  map_obj <- map_obj %>%
    mutate(area = st_area(.))
  
  # Function 
  total_area <- sum(map_obj$area)
  average_density <- N / total_area
  
  map_obj <- map_obj %>%
    mutate(density = average_density * density / mean(density, na.rm = TRUE))
  
  # Create grid
  grid <- map_obj %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1],
           Y = st_coordinates(.)[,2]) %>%
    as.data.frame() %>%
    select("X","Y","density") %>%
    as.im()

  # Inhomogenous Poisson point process
  ppp <- rpoispp(lambda = grid, drop = TRUE)
  sim_ind <- data.frame(x = ppp$x, y = ppp$y)

  # Possibility to add group size
  sim_ind <- sim_ind %>%
    mutate(size = rpois(nrow(sim_ind), lambda = (mean_group_size - 1)) + 1)
  
  return(sim_ind)
}

