# Generated by fusen: do not edit by hand


#' Simulate individuals with a inhomogenous Poisson point process
#'
#' @param map_obj Dataframe. Sf map with a colum containg density informations density_m
#'
#' @importFrom glue glue
#' @importFrom assertthat assert_that
#' @importFrom dplyr mutate select filter
#' @importFrom sf st_centroid st_coordinates st_crs
#' @importFrom sp coordinates<- proj4string<- gridded<- CRS
#' @importFrom maptools as.im.SpatialGridDataFrame
#'
#' @return Dataframe. Les localisations des individus.
#' @export

#' @examples
#' 
#' library(ggplot2)
#' data("shape_courseulles")
#' 
#' # First, create a map with a gradient density from the North with 500 individuals in the area
#' map_obj <- create_density_map(shape_obj = shape_courseulles,
#'                               N = 200,
#'                               grid_size = 1000,
#'                               density_type = "gradient",
#'                               gradient_direction = "N",
#'                               wavelength = 30000,
#'                               amplitude = 70
#'                               
#' )
#' 
#' 
#' # Then simulate the presence of individuals in the study area with a inhomogenous Poisson point process
#' obs_obj <- simulate_ind(map_obj = map_obj)
#' 
#' 
#' # Plot results
#' ggplot() +
#'     geom_sf(data = map_obj, aes(fill = density)) +
#'     geom_point(data = obs_obj, aes(x = x, y = y))
#'   
simulate_ind <- function(map_obj) {
  
  # Function checks
  
  
  assert_that(inherits(map_obj, "sf"))
  if (!all(c("density") %in% names(map_obj))) {stop("map_obj must contain `density` column. Verify your column names.")}
  assert_that(is.numeric(map_obj$density))
  
  
  # Function 
  # st_make_grid
  
  # Create grid
  grid <- map_obj %>%
    st_centroid() %>%
    mutate(X = st_coordinates(.)[,1],
           Y = st_coordinates(.)[,2]) %>%
    as.data.frame() %>%
    select("X","Y","density")
  
  
  # Convert in grid class
  coordinates(grid) <- ~ X + Y
  proj4string(grid) <- CRS(st_crs(2154)$proj4string)
  gridded(grid) <- TRUE
  X_grid <- maptools::as.im.SpatialGridDataFrame(grid)
  
  # Inhomogenous Poisson point process
  ppp <- spatstat.core::rpoispp(lambda = X_grid, drop = TRUE)
  sim_ind <- data.frame(x = ppp$x, y = ppp$y)
  
  # Possibility to add group size
  sim_ind <- sim_ind %>%
    mutate(size = 1)
  
  return(sim_ind)
  
}

